server:
  port: 8081
#  servlet:
#    context-path: /api/v1
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spring_lesson_10
    username: root
    password: PLS37pXTZ
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    hibernate:
      ddl-auto: validate
#  mvc:
#    view:
#      prefix: /WEB-INF/jsp/
#      suffix: .jsp
