server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/Lesson_12
    username: root
    password: PLS37pXTZ
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: false
    hibernate:
      ddl-auto: update
  thymeleaf:
    enabled: true
    encoding: UTF-8
    check-template-location: true
    prefix: classpath:/templates/
    suffix: .html
